[workspace]
members = [
  "tower-http",
  "examples/*",
]

[patch.crates-io]
# for `Frame::map_data`
http-body = { git = "https://github.com/hyperium/http-body", rev = "7bf321acbb422214c89933c103417bcfe3892aed" }
