[package]
name = "tower-request-modifier"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"

[dependencies]
futures = "0.1"
http = "0.1"
tower-service = "0.2"

[dev-dependencies]
tower-test = { git = "https://github.com/tower-rs/tower" }
